title: "CASS"
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme
  - jemoji

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Aux links for the upper right navigation
aux_links:
  "Toledo":
    - "//toledo.kuleuven.be/portal/#/home"
  "RARS":
    - "//github.com/TheThirdOne/rars/releases"
  "Risc-V Card":
    - "/files/riscv-card.pdf"
  "Syllabus":
    - "//onderwijsaanbod.kuleuven.be/syllabi/n/H01P5BN.htm"
  "Uurrooster":
    - "//www.kuleuven.be/sapredir/uurrooster/pre_laden.htm?OBJID=55589533&OTYPE=SM&TAAL=N&SEL_JAAR=2021"
  "Videos (last year)":
    - "https://www.youtube.com/playlist?list=PLMXWnt556xY4Sexd5FMBc-ZF7pFb2SLnU"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

collections:
  course:
    permalink: "/:collection/:path/"
    output: true
  exercises:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    course:
      name: Computer Architecture and System Software
    exercises:
      name: Exercise sessions
    tutorials:
      name: Tutorials

kramdown:
  toc_levels: "1..3"

solutions:
  show_session_1: false
  show_session_2: false
  show_session_3: false
  show_session_4: false
  show_session_5: false
  show_session_6: false
  show_session_7: false
  show_session_8: false
